config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  resources :groups

  get '/auth/:provider', to: 'sessions#new', as: 'sign_in'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :votes
 	has_many :images

 	mount_uploader :photo, PhotoUploader
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :group
  has_many :votes

  has_attached_file :pic, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :groups
	has_many :votes

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.name = auth.info.name
		end
	end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :group
  belongs_to :vote
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :current_user, only: [:show, :new, :create, :destroy]
	before_action :find_graph, only: [:index]

	def index
		@group = Group.offset(rand(Group.count)).first 

		respond_to do |format|
			format.html
			format.js 
		end
	end

	def show
		@group = Group.find(params[:id])
	end

	def new
		@group = current_user.groups.new
	end

	def create
		@group = current_user.groups.create(group_params)

		if @group.save
			redirect_to groups_path
		else
			redirect_to groups_path
		end
	end

	def destroy
		@group = Group.find(parmas[:id])
		@group.destroy

		redirect_to groups_path
		#have their old groups destroy upon creating a new one
		#the .first_or_create method might come in handy
	end

	private

	def group_params
		params.require(:group).permit(:name, :user_id)
	end

	def find_graph
		@graph = Koala::Facebook::API.new(session[:token])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def create
		oauth = request.env['omniauth.auth']
		@user = User.from_omniauth(oauth)
		session[:token] = oauth['credentials']['token']

		if @user.persisted?
			session[:user_id] = @user.id 
			redirect_to groups_path
		else 
			session[:user_id] = nil
			redirect_to groups_path
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

	def omniauth_failure
		redirect_to root_path
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_form.html.erb
<%= form_for (@organization, @image) do |f| %>
<%= f.submit %>
<% end %>

app/views/groups/index.html.erb
<h1>Groups Index</h1>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>

<% @profile = @graph.get_object("me") %>
<%= @profile["name"] %><br>
<%= link_to 'Sign Out', sign_out_path, method: :delete %>

<br>

<% @albums = @graph.get_connections("me", "albums?fields=name,photos{name, images{source}}") %>
<% @albums.at(3)["photos"]["data"].each do |data| %>
	<div id="<%= data["id"] %>" class="outer" data-toggle="modal" data-target="#myModal">
    <%= image_tag data["images"].first["source"] %>
  </div>
<% end %>

<script>
$(document).ready(function() {
	$(".outer").click(function (e){
    e.preventDefault();
    $(".modal-body").html($(this).html());
  });
});
</script>

app/views/groups/select.js.erb
$(document).ready(function() {
	$(".outer").click(function (e){
    e.preventDefault();
    $(".modal-body").html($(this).html());
  });
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RateMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

    <body>

        <div class="site-wrapper">

          <div class="site-wrapper-inner">

            <div class="cover-container">

              <div class="masthead clearfix">
                <div class="inner">
                  <h3 class="masthead-brand">My Best Me</h3>           
                </div>
              </div>

              <div class="inner cover">
                <h1 class="cover-heading">Step one:</h1><br>
                <p class="lead">Sign up using Facebook to access your pictures</p>
                <h1 class="cover-heading">Step two:</h1><br>
                <p class ="lead">Create a group of photos that you want people to vote on</p>
                <h1 class="cover-heading">Step three:</h1><br>
                <p class ="lead">Vote on at least 3 groups from other people to see your results</p>
                <br>

                <%= link_to 'auth/facebook', class: "btn btn-social btn-facebook" do %>
        						<i class="fa fa-facebook"></i> Sign in with Facebook
                <% end %>

              </div>

            </div>

          </div>

        </div>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="../../dist/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
      </body>
</html>